version: "3.8"
services:
  centrifugo:
    image: centrifugo/centrifugo:v2.5
    command: centrifugo -c config.json
    volumes:
      - ./tmp/centrifugo:/centrifugo
    ports:
      - 127.0.0.1:9000:8000
