
web:
  # Use existing image
  image: alextanhongpin/node-hello
  # build: .
  links: 
    - redis
  ports:
    # Expose the port 4000
    - "4000:4000"
  environment:
    # Listen to port *:4000
    - PORT=4000
    # Link to client redis:6379
    - REDIS_HOST=redis://redis:6379
  volumes:
    - "./app:/usr/src/app"
redis:
  image: redis
  ports:
    - "6379:6379"