
web:
  image: alextanhongpin/node-hello
  # build: .
  links: 
    - redis
  ports:
    # Expose the port 4000
    - "4000:4000"
  environment:
    # Use port 4000 for express
    - PORT=4000
    # Link to redis and connect to hostname
    - REDIS_HOST=redis://redis:6379
  volumes:
    - "./app:/usr/src/app"
redis:
  image: redis
  ports:
    - "6379:6379"