version: '3.6'
services:
  mysql:
    image: mysql:8.0.11
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_USER=root
    - MYSQL_PASSWORD=123456
    - MYSQL_DATABASE=test
    volumes:
    - ./tmp/mysql:/var/lib/mysql
