version: '2'
services: 
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    ports: 
      - 5432:5432
  kong:
    image: kong:latest
    depends_on: 
      - postgres
    links:
      - postgres
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    command: kong start
